version: "0.1"
volumes:
  mysql_data:
    driver: local
services:
  films:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/film-db?createDatabaseIfNotExist=true&useSSL=true
      - spring.datasource.username=bd_user
      - spring.datasource.password=bd_pass
      - spring.jpa.database=mysql
  mysql_db:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=securePass
      - MYSQL_USER=bd_user
      - MYSQL_PASSWORD=bd_pass
      - MYSQL_DATABASE=film-db
    volumes:
      - "mysql_data:/var/lib/mysql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
